name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: 'Prepare: checkout'
        uses: actions/checkout@v2

      - name: 'Prepare: setup OpenJDK 11'
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'

      - name: 'Prepare: setup Node 16'
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: 'Prepare: install dependencies'
        run: yarn

      - name: 'Run: lint'
        run: yarn lint
