name: CI/CD

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ios-build:
    name: iOS build
    runs-on: macos-latest
      
    steps:
      - name: 'Prepare: checkout'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: 'Prepare: setup node'
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: 'Prepare: install dependencies'
        run: yarn

      - name: 'Prepare: set build version'
        run: yarn bump 1.2.3 12

      - name: 'Run: lint'
        run: yarn lint

      - name: 'Prepare: pods cache'
        uses: actions/cache@v2
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
        
      - name: 'Prepare: ruby'
        uses: ruby/setup-ruby@v1
        with:
          bundler: "Gemfile.lock"
          bundler-cache: true

      - name: 'Prepare: install pods'
        working-directory: ios
        run: pod install

      - name: 'Run: build'
        run: yarn ios

  android-build:
    name: Android build
    runs-on: ubuntu-latest

    steps:
      - name: 'Prepare: checkout'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: 'Prepare: setup node'
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: 'Prepare: install dependencies'
        run: yarn

      - name: 'Prepare: set build version'
        run: yarn bump 1.2.3 12

      - name: 'Run: lint'
        run: yarn lint

      - name: 'Prepare: setup openjdk'
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
        
      - name: 'Prepare: ruby'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: 'Run: build'
        run: yarn android

  tag:
    name: Tag creation
    runs-on: ubuntu-latest
    needs:
      - ios-build
      - android-build

    steps:
      - name: 'Prepare: checkout'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
