name: CI/CD

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ios-build-cache:
    name: iOS build
    runs-on: macos-latest
      
    steps:
      - name: 'Prepare: checkout'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: 'Prepare: setup node'
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: 'Prepare: install dependencies'
        run: yarn

      - name: 'Run: lint'
        run: yarn lint

      - name: 'Prepare: build cache'
        uses: mikehardy/buildcache-action@v1
        
      - name: 'Prepare: ruby'
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: 'Prepare: install pods'
        working-directory: ios
        run: pod install

      - name: 'Run: build'
        run: yarn ios
